{"name": "test_get_status_codes_default[302-200]", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа: 404\nassert 404 == 200\n  +404\n  -200", "trace": "test_status_codes.py:17: in test_get_status_codes_default\n    assert r.status_code == result, f\"Неверный код ответа: {r.status_code}\"\nE   AssertionError: Неверный код ответа: 404\nE   assert 404 == 200\nE     +404\nE     -200\n        code       = 302\n        r          = <Response [404]>\n        result     = 200\n        url        = 'https://httpbin.org/status/302'"}, "attachments": [{"name": "log", "source": "8738153d-8594-455b-8a89-bf72ce198b1f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "4548d726-ccf1-4f07-b048-0729ca001397-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "code", "value": "302"}, {"name": "result", "value": "200"}], "start": 1596531133476, "stop": 1596531139838, "uuid": "7ca677ae-4da0-4ce5-85a3-b32749f46627", "historyId": "01d89868c3dc48bfd66c1092af308ccd", "testCaseId": "80afa581fd05c978edda73147ca515a8", "fullName": "test_status_codes#test_get_status_codes_default", "labels": [{"name": "suite", "value": "test_status_codes"}, {"name": "host", "value": "S340"}, {"name": "thread", "value": "32140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_status_codes"}]}